Use new blockcontext constructor (#4419)

diff --git a/tools/.ci/pre-commit b/tools/.ci/pre-commit
--- a/tools/.ci/pre-commit
+++ b/tools/.ci/pre-commit
@@ -42,28 +42,30 @@ execute_cmd() {
 }
 
 function check_codeFormat() {
-  # if clang-format command not exist, print log and return directly
-  if ! command -v ${check_script} &>/dev/null; then
-    LOG_INFO "clang-format command not found, please install it, skip by default."
-    exit 0
-  fi
-  # if clang-format first version less than 15 skip check
-  if [ $(clang-format --version | awk '{print $3}' | awk -F '.' '{print $1}') -lt 15 ]; then
-    LOG_INFO "clang-format version less than 15, skip check."
-    exit 0
-  fi
-  # Redirect output to stderr.
-  exec 1>&2
-  sum=0
-  for file in $(git diff-index --name-status HEAD^ -- | grep -v D | grep -E '\.[ch](pp)?$' | awk '{print $2}'); do
-    clang-format -style=file -i $file --dry-run --Werror
-    sum=$(expr ${sum} + $?)
-    execute_cmd "$check_script -style=file -i $file"
-  done
-
-  if [ ${sum} -ne 0 ]; then
-    echo "######### ERROR: Format check failed, please adjust them before commit"
-    exit 1
+  if [ "$(uname)" = "Darwin" ]; then
+    # if clang-format command not exist, print log and return directly
+    if ! command -v ${check_script} &>/dev/null; then
+      LOG_INFO "clang-format command not found, please install it, skip by default."
+      exit 0
+    fi
+    # if clang-format first version less than 15 skip check
+    if [ $(clang-format --version | awk '{print $3}' | awk -F '.' '{print $1}') -lt 15 ]; then
+      LOG_INFO "clang-format version less than 15, skip check."
+      exit 0
+    fi
+    # Redirect output to stderr.
+    exec 1>&2
+    sum=0
+    for file in $(git diff-index --name-status HEAD^ -- | grep -v D | grep -E '\.[ch](pp)?$' | awk '{print $2}'); do
+      clang-format -style=file -i $file --dry-run --Werror
+      sum=$(expr ${sum} + $?)
+      execute_cmd "$check_script -style=file -i $file"
+    done
+  
+    if [ ${sum} -ne 0 ]; then
+      echo "######### ERROR: Format check failed, please adjust them before commit"
+      exit 1
+    fi
   fi
 }
 check_codeFormat
