<fix>(sdk,build): try to fix cpp sdk link error in windows, fix pre-commit overcover. (#4084)

diff --git a/tools/.ci/pre-commit b/tools/.ci/pre-commit
--- a/tools/.ci/pre-commit
+++ b/tools/.ci/pre-commit
@@ -7,8 +7,8 @@
 # @ date    : 2023
 
 SHELL_FOLDER=$(
-    cd $(dirname $0)
-    pwd
+  cd $(dirname $0)
+  pwd
 )
 
 check_script="clang-format"
@@ -20,40 +20,45 @@ license_line=20
 skip_check_words="sync code|release"
 
 LOG_ERROR() {
-    content=${1}
-    echo -e "\033[31m"${content}"\033[0m"
+  content=${1}
+  echo -e "\033[31m"${content}"\033[0m"
 }
 
 LOG_INFO() {
-    content=${1}
-    echo -e "\033[32m"${content}"\033[0m"
+  content=${1}
+  echo -e "\033[32m"${content}"\033[0m"
 }
 
 execute_cmd() {
-    command="${1}"
-    eval ${command}
-    ret=$?
-    if [ $ret -ne 0 ]; then
-        LOG_ERROR "FAILED of command: ${command}"
-        exit 1
-    else
-        LOG_INFO "SUCCESS of command: ${command}"
-    fi
+  command="${1}"
+  eval ${command}
+  ret=$?
+  if [ $ret -ne 0 ]; then
+    LOG_ERROR "FAILED of command: ${command}"
+    exit 1
+  else
+    LOG_INFO "SUCCESS of command: ${command}"
+  fi
 }
 
 function check_codeFormat() {
-    # Redirect output to stderr.
-    exec 1>&2
-    sum=0
-    for file in $(git diff-index --name-status HEAD^ -- | grep -v D | grep -E '\.[ch](pp)?$' | awk '{print $2}'); do
-        clang-format -style=file -i $file --dry-run --Werror
-        sum=$(expr ${sum} + $?)
-        execute_cmd "$check_script -style=file -i $file"
-    done
+  # if clang-format command not exist, print log and return directly
+  if ! command -v ${check_script} &>/dev/null; then
+    LOG_INFO "clang-format command not found, please install it, skip by default."
+    exit 0
+  fi
+  # Redirect output to stderr.
+  exec 1>&2
+  sum=0
+  for file in $(git diff-index --name-status HEAD^ -- | grep -v D | grep -E '\.[ch](pp)?$' | awk '{print $2}'); do
+    clang-format -style=file -i $file --dry-run --Werror
+    sum=$(expr ${sum} + $?)
+    execute_cmd "$check_script -style=file -i $file"
+  done
 
-    if [ ${sum} -ne 0 ]; then
-        echo "######### ERROR: Format check failed, please adjust them before commit"
-        exit 1
-    fi
+  if [ ${sum} -ne 0 ]; then
+    echo "######### ERROR: Format check failed, please adjust them before commit"
+    exit 1
+  fi
 }
 check_codeFormat
